### ISSUE TITLE
Fatal error: Call to undefined method Nyholm\Psr7\Response::getContent()

### ISSUE THREAD

**Issue by herbert-roth** [kielabokkie/jsonapi-behat-extension#11]
The Nyholm\Psr7\Response does not have a getConntent method!!!

This is a show stopper. 
Oauth and response validation are broken.

sendOauthRequest:

protected function sendOauthRequest(array $payload)
    {
        $url = sprintf('%s%s', $this->baseUrl, $this->parameters['oauth']['uri']);

        $response = $this->client->post($url, $this->headers, json_encode($payload));
        **$responseContent = json_decode($response->getContent());**

public function iGetAResponse($statusCode)
    {
        $response = $this->getResponse();

        $contentType = $response->getHeader('Content-Type');
        **$bodyOutput = $response->getContent();**

And many other places to fix..

**Comment by aguidis** [comment]
I just got this error too

**Comment by kielabokkie** [comment]
Hi guys, I'm super swamped with work after the holidays but I'll try to find some time to look into this in the next few days. If any of you know a solution let me know so this can be fixed faster.

**Comment by kielabokkie** [comment]
@herbert-roth @aguidis I've tagged version [v2.0.3](https://github.com/kielabokkie/jsonapi-behat-extension/releases/tag/v2.0.3) which should fix this issue. Let me know if this solved it for you guys.

**Comment by kielabokkie** [comment]
I'm going to assume that this issue is solved. Let me know if this is not the case 😉️
