### ISSUE TITLE
Update buzz (for PHP 8 support)

### ISSUE THREAD

**Issue by pfrenssen** [kielabokkie/jsonapi-behat-extension#17]
We are currently locked on `kriswallsmith/buzz 0.15.2` but this does not support PHP 8. We will have to update to the stable v1.x version.

This has a drawback though: buzz 1.x no longer supports PHP 5, so in case we update we will have to drop PHP 5 support as well, or find a solution around it.

* We create a new major v4.0.0 release with PHP 8 support, while still maintaining v3.x for people who need PHP 5.
* We write a wrapper class around buzz which handles both 0.15.2 and 1.x, and keep support for PHP 5 in our 3.x branch moving forward.

**Comment by kielabokkie** [comment]
Thanks for submitting this issue @pfrenssen

I think tagging a new major version 4.x for PHP 8 and up while keeping the 3.x for PHP 5 is fine.

**Comment by kielabokkie** [comment]
Unfortunately it's not as easy as just updating the dependencies but made some good progress on this. Should have something ready soon.

**Comment by kielabokkie** [comment]
@pfrenssen I just released v4.0.0 that adds support for PHP 8.x.

It was a bit of a rewrite and I also tidied things up along the way. I don't have any active projects myself anymore that use Behat so I did some minimal testing but nothing thorough so I would appreciate it if you can give it a good whirl and let me know how it went.

**Comment by pfrenssen** [comment]
Thanks for the quick fix! This is working for us, our tests are green!
