### ISSUE TITLE
Fresh install, extension could not be located

### ISSUE THREAD

**Issue by damian-pf** [kielabokkie/jsonapi-behat-extension#6]
Hi there,

I am just setting up a new project on Laravel 5.4 and have pulled in your package as one of my first steps in setting up the project.

When I run `vendor/bin/behat` I get the following error

```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
`Kielabokkie\BehatJsonApi` extension file or class could not be located.
```

I tried `composer dump` and `php artisan cache:clear` (for good measure) but no luck

However running `composer dump -o` does fix the issue. Not sure what is causing the bug but it seems strange that the optimised auto-loader is all that fixes it.

**Comment by kielabokkie** [comment]
@damian-nz This is a curios issue that has been happening on occasion on L5.3 too. I'll have a look again soon and see if I can solve this once and for all.
